language: objective-c
env:
  # same as specified in xcodeproj
  - RVM_RUBY_VERSION=ruby-1.9.3-p392 CI=true'
before_install: source ~/.rvm/scripts/rvm && rvm install $RVM_RUBY_VERSION && rvm use $RVM_RUBY_VERSION
script: bundle exec rake spec build